# Generated by Django 3.0.2 on 2020-01-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_time.Attendance')),
            ],
        ),
    ]
