# Generated by Django 3.0.2 on 2020-01-12 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('hourly_wage', models.PositiveIntegerField(default=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='manage_time.Member'),
            preserve_default=False,
        ),
    ]
