# Generated by Django 3.0.2 on 2020-01-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0002_auto_20200112_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='line_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_time.LineID'),
        ),
    ]
