# Generated by Django 3.0.2 on 2020-01-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0003_auto_20200112_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('money', models.PositiveIntegerField(verbose_name='金額')),
            ],
            options={
                'verbose_name': '日当',
                'verbose_name_plural': '日当',
            },
        ),
    ]
