# Generated by Django 3.0.2 on 2020-01-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0003_auto_20200112_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-clock_in_time']},
        ),
        migrations.AlterField(
            model_name='break',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_time.Attendance'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='金額')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_time.Attendance')),
            ],
            options={
                'verbose_name': '日当',
                'verbose_name_plural': '日当',
            },
        ),
    ]
