# Generated by Django 3.0.2 on 2020-01-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0004_auto_20200113_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_time.Attendance', unique=True),
        ),
    ]
