# Generated by Django 3.0.2 on 2020-01-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0004_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_time.Attendance'),
        ),
    ]
