# Generated by Django 3.0.2 on 2020-01-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0005_auto_20200113_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_time.Attendance'),
        ),
    ]
