# Generated by Django 3.0.2 on 2020-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0005_auto_20200113_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='money',
            field=models.FloatField(verbose_name='金額'),
        ),
    ]
