# Generated by Django 3.0.2 on 2020-01-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0006_auto_20200113_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='date',
        ),
        migrations.AddField(
            model_name='salary',
            name='attendance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_time.Attendance'),
            preserve_default=False,
        ),
    ]
