# Generated by Django 3.0.2 on 2020-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0006_auto_20200113_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_time',
            field=models.DurationField(null=True),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
