# Generated by Django 3.0.2 on 2020-01-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0007_auto_20200113_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-clock_in_time']},
        ),
    ]
