# Generated by Django 3.0.2 on 2020-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_time', '0008_auto_20200115_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='work_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
